name: "Build"
on:
  push:
  schedule: # Test daily.
    - cron: 0 11 * * *

jobs:
  run-godot:
    name: ${{ matrix.os }} ${{ matrix.bits }}bit ${{ matrix.version }} ${{ matrix.mono && 'mono' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        bits: [64, 32]
        mono: [true, false]
        version:
          [
            "v3.1-stable",
            "v3.1.2-stable",
            "v3.2.3-stable",
            "v3.3.4-stable",
            "v3.4-stable",
            "v3.4.1-rc3",
          ]
        exclude:
          - os: macos-latest
            bits: 32

          # Issue: https://github.com/godotengine/godot/issues/27496
          - os: ubuntu-latest
            bits: 32
            mono: false
            version: "v3.1-stable"
          - os: ubuntu-latest
            bits: 32
            mono: false
            version: "v3.1.2-stable"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot
        id: setup-godot
        uses: ./
        with:
          version: ${{ matrix.version }}
          bits: ${{ matrix.bits }}
          mono: ${{ matrix.mono }}
      - shell: bash
        run: godot --editor --quit

  with_alias:
    name: "with alias"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot with alias
        uses: ./
        with:
          alias: coolGameEngine
      - name: Run Godot with alias
        run: coolGameEngine --editor --quit
      - name: Setup Godot v3.3.2 with alias
        uses: ./
        with:
          version: 3.3.2
          alias: godot-3.3.2
      - name: Setup Godot v3.2 with alias
        uses: ./
        with:
          version: 3.2
          alias: godot-3.2
      - name: Check versions
        run: |
          godot-3.3.2 --version || true
          godot-3.2 --version || true

  no_cache:
    name: "no cache"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot without using cache
        uses: ./
        with:
          cache: false
